name: wallet
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.9.3 <3.0.0'

dependencies:
  jose: ^0.2.1+1
  wallet_core: ^0.2.4+18
  bitcoin_flutter: ^2.0.1
  # path_provider: 0.3.9
  secp256k1: ^0.1.1
  cbor: ^3.2.0
  x509: ^0.1.3
  sembast: ^2.4.8
  pedantic: ^1.9.0
  js: ^0.6.2
  cryptography: ^1.4.1
  pointycastle: ^1.0.1
  ed25519_hd_key: ^1.0.1
  sqflite_common_ffi  : ^1.1.1
  sembast_sqflite  : ^1.0.0


dev_dependencies:
  test: ^1.14.4
